language: java
dist: trusty

jdk:
  - oraclejdk8

env:
  - TEST_DIR=fc-java-events
  - TEST_DIR=fc-java-core
  - TEST_DIR=fc-java-common
script: cd $TEST_DIR  && mvn clean package install -DskipTests -Dgpg.skip
